import Chat from '../models/Chat.js';
import { Op } from 'sequelize';

// @desc    Send message to AI tutor
// @route   POST /api/tutor/chat
// @access  Private
export const sendMessage = async (req, res) => {
  try {
    const { text } = req.body;

    if (!text || !text.trim()) {
      return res.status(400).json({ message: 'Message text is required' });
    }

    // Save user message
    const userMessage = await Chat.create({
      userId: req.user.id,
      text: text.trim(),
      isAI: false,
    });

    // TODO: Integrate with AI API (OpenAI, etc.)
    // For now, return a simple response
    const aiResponseText = `I understand your question about "${text.trim()}". Let me help you with that! This is a placeholder response. In production, this would be generated by an AI model.`;

    // Save AI response
    const aiMessage = await Chat.create({
      userId: req.user.id,
      text: aiResponseText,
      isAI: true,
    });

    res.json({
      userMessage: {
        id: userMessage.id,
        text: userMessage.text,
        time: userMessage.timestamp,
        isAI: false,
      },
      aiMessage: {
        id: aiMessage.id,
        text: aiMessage.text,
        time: aiMessage.timestamp,
        isAI: true,
      },
    });
  } catch (error) {
    console.error('Send message error:', error);
    res.status(500).json({ message: 'Server error' });
  }
};

// @desc    Get chat history
// @route   GET /api/tutor/history
// @access  Private
export const getChatHistory = async (req, res) => {
  try {
    const limit = parseInt(req.query.limit) || 50;

    const messages = await Chat.findAll({
      where: { userId: req.user.id },
      order: [['timestamp', 'DESC']],
      limit,
      attributes: { exclude: ['userId'] },
    });

    // Format messages for frontend
    const formattedMessages = messages.reverse().map((msg) => ({
      id: msg.id,
      text: msg.text,
      time: new Date(msg.timestamp).toLocaleTimeString('en-US', {
        hour: '2-digit',
        minute: '2-digit',
      }),
      isAI: msg.isAI,
    }));

    res.json(formattedMessages);
  } catch (error) {
    console.error('Get chat history error:', error);
    res.status(500).json({ message: 'Server error' });
  }
};

// @desc    Get chat statistics
// @route   GET /api/tutor/stats
// @access  Private
export const getChatStats = async (req, res) => {
  try {
    const totalMessages = await Chat.count({
      where: {
        userId: req.user.id,
        isAI: false,
      },
    });

    // Simple topic extraction (in production, use NLP)
    const uniqueMessages = await Chat.findAll({
      where: {
        userId: req.user.id,
        isAI: false,
      },
      attributes: ['text'],
      group: ['text'],
    });

    const topicsCovered = Math.min(uniqueMessages.length, 8); // Placeholder

    res.json({
      questionsAsked: totalMessages,
      topicsCovered,
    });
  } catch (error) {
    console.error('Get chat stats error:', error);
    res.status(500).json({ message: 'Server error' });
  }
};
